#homepage
app_homepage:
    path:     /{_locale}
    defaults: { _controller: AppBundle:Default:index, _locale: en }
    requirements:
      _locale: en|pl

#about_us
app_about_us:
    path:     /about-us
    defaults: { _controller: AppBundle:Default:about_us }

#news
app_news:
    path:     /news
    defaults: { _controller: AppBundle:News:index }
#add news details here
app_news_details:
    path:     /news/{id}
    requirements:
            id:  \d+
    defaults: { _controller: AppBundle:News:getOne }