AppBundle\Entity\News:
    type:  entity
    table: news
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            lenght: 255
            nullable: false
        slug:
            type: string
            lenght: 255
            nullable: false
            unique: true
        content:
            type: text
            nullable: false
        created_at:
            type: datetime